// packages/vue/src/Button.vue
<template>
  <button :class="['btn', buttonType, buttonSize, { 'btn-full-width': fullWidth }]" :disabled="isDisabled"
    @click="onClick">
    <template v-if="isLoading">
      <span>Loading...</span>
    </template>
    <template v-else>
      <i v-if="icon" :class="iconClass"></i>
      <slot>{{ label }}</slot>
    </template>
  </button>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import '../../styles/src/components/button.css'

export default defineComponent({
  name: 'Button',
  props: {
    label: {
      type: String,
      required: false,
    },
    type: {
      type: String,
      default: 'primary', // 'primary', 'secondary', 'danger'
    },
    size: {
      type: String,
      default: 'medium', // 'small', 'medium', 'large'
    },
    icon: {
      type: String,
      default: '', // Icon class for the button
    },
    isLoading: {
      type: Boolean,
      default: false,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    fullWidth: {
      type: Boolean,
      default: false,
    },
  },
  computed: {
    buttonType() {
      return `btn-${this.type}`;
    },
    buttonSize() {
      return `btn-${this.size}`;
    },
    isDisabled() {
      return this.disabled || this.isLoading;
    },
    iconClass() {
      return this.icon ? `icon-${this.icon}` : '';
    },
  },
  methods: {
    onClick(event: MouseEvent) {
      if (!this.isDisabled) {
        this.$emit('click', event);
      }
    },
  },
});
</script>

// packages/react/src/Button.tsx
import React from 'react';
import '../../styles/src/components/button.css';

interface Props {
  label?: string;
  type?: 'primary' | 'secondary' | 'danger';
  size?: 'small' | 'medium' | 'large';
  icon?: string;
  isLoading?: boolean;
  disabled?: boolean;
  fullWidth?: boolean;
  onClick?: (event: React.MouseEvent<HTMLButtonElement>) => void;
}

const Button: React.FC<Props> = ({
  label,
  type = 'primary',
  size = 'medium',
  icon,
  isLoading = false,
  disabled = false,
  fullWidth = false,
  onClick,
}) => {
  // Compute button classes
  const buttonType = `btn-${type}`;
  const buttonSize = `btn-${size}`;
  const isDisabled = disabled || isLoading;
  const iconClass = icon ? `icon-${icon}` : '';

  // Handle button click
  const handleClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    if (!isDisabled && onClick) {
      onClick(event);
    }
  };

  return (
    <button
      className={`btn ${buttonType} ${buttonSize} ${
        fullWidth ? 'btn-full-width' : ''
      }`}
      disabled={isDisabled}
      onClick={handleClick}
    >
      {isLoading ? (
        <span>Loading...</span>
      ) : (
        <>
          {icon && <i className={iconClass}></i>}
          {label}
        </>
      )}
    </button>
  );
};

export default Button;
