// packages/vue/src/Dropdown.vue
<template>
    <div class="dropdown" @click="toggleDropdown">
        <button class="dropdown-toggle">
            {{ displayText }} <!-- Using a computed property here -->
            <span class="arrow" :class="{ 'is-active': isOpen }">▼</span>
        </button>
        <ul v-if="isOpen" class="dropdown-menu">
            <li v-for="(option, index) in options" :key="index" class="dropdown-item"
                @click.stop="selectOption(option)">
                {{ option }}
            </li>
        </ul>
    </div>
</template>

<script>
import { defineComponent } from 'vue';
import '../../styles/src/components/dropdown.css';

export default defineComponent({
    name: 'Dropdown',
    props: {
        options: {
            type: Array,
            required: true,
        },
        label: {
            type: String,
            default: 'Select an option',
        },
    },
    data() {
        return {
            isOpen: false,
            selectedOption: null,
        };
    },
    computed: {
        displayText() {
            // If selectedOption is null, show the label; otherwise, show the selected option
            return this.selectedOption || this.label;
        },
    },
    methods: {
        toggleDropdown() {
            this.isOpen = !this.isOpen;
        },
        selectOption(option) {
            this.selectedOption = option;
            this.isOpen = false;
            this.$emit('option-selected', option); // Emit the selected option
        },
    },
});
</script>

// packages/react/src/Dropdown.tsx
import React, { useState } from 'react';
import '../../styles/src/components/dropdown.css';

// Define the prop types for the Dropdown component
interface DropdownProps {
  options: string[]; // An array of strings for the options
  label?: string; // Optional label
  onOptionSelected: (option: string) => void; // Callback when an option is selected
}

const Dropdown: React.FC<DropdownProps> = ({
  options,
  label = 'Select an option',
  onOptionSelected,
}) => {
  const [isOpen, setIsOpen] = useState<boolean>(false); // Type for isOpen state
  const [selectedOption, setSelectedOption] = useState<string | null>(null); // Type for selectedOption state

  const toggleDropdown = () => {
    setIsOpen(!isOpen);
  };

  const selectOption = (option: string) => {
    // Type for the option parameter
    setSelectedOption(option);
    setIsOpen(false);
    onOptionSelected(option); // Call the prop function when an option is selected
  };

  const displayText = selectedOption || label;

  return (
    <div className="dropdown" onClick={toggleDropdown}>
      <button className="dropdown-toggle">
        {displayText}
        <span className={`arrow ${isOpen ? 'is-active' : ''}`}>▼</span>
      </button>
      {isOpen && (
        <ul className="dropdown-menu">
          {options.map((option, index) => (
            <li
              key={index}
              className="dropdown-item"
              onClick={(e) => {
                e.stopPropagation();
                selectOption(option);
              }}
            >
              {option}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
};

export default Dropdown;
