// packages/react/src/Checkbox.tsx
import React from 'react';
import '../../styles/src/components/checkbox.css';

interface CheckboxProps {
  checked: boolean;
  value?: string;
  onChange?: (checked: boolean) => void; // Optional prop for handling change
}

const Checkbox: React.FC<CheckboxProps> = ({ checked, value, onChange }) => {
  const handleCheckboxChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const isChecked = event.target.checked;
    if (onChange) {
      onChange(isChecked); // Call the onChange prop if provided
    }
  };

  return (
    <label className="checkbox-label">
      <input
        type="checkbox"
        checked={checked}
        onChange={handleCheckboxChange}
        className="checkbox-input"
      />
      {value && <span className="checkbox-value">{value}</span>}
    </label>
  );
};

export default Checkbox;

// packages/vue/src/Checkbox.vue
<template>
    <label class="flex items-center">
        <input type="checkbox" :value="value" v-model="proxyChecked" class="checkbox-input" />
        <span class="checkbox-value">
            {{ value }} <!-- Direct access to value prop -->
        </span>
    </label>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import '../../styles/src/components/checkbox.css';

const emit = defineEmits(['update:checked']);

const props = defineProps<{
    checked: boolean;
    value?: any;
}>();

const proxyChecked = computed({
    get() {
        return props.checked;
    },
    set(val) {
        emit('update:checked', val);
    },
});
</script>
