// packages/dollhouse-designs/src/components/react/Button.tsx
import React from 'react';
import '../styles/button.css'; // Ensure shared styles

interface ButtonProps {
  label: string;
  primary?: boolean;
  secondary?: boolean;
  danger?: boolean;
  size?: 'small' | 'medium' | 'large';
  backgroundColor?: string;
  onClick?: () => void;
}

const Button: React.FC<ButtonProps> = ({
  label,
  primary,
  secondary,
  danger,
  size = 'medium',
  backgroundColor,
  onClick,
}) => {
  const classes = [
    'button',
    primary && 'button-primary',
    secondary && 'button-secondary',
    danger && 'button-danger',
    `button-${size}`,
  ]
    .filter(Boolean)
    .join(' ');

  const style = backgroundColor ? { backgroundColor } : {};

  return (
    <button type="button" className={classes} style={style} onClick={onClick}>
      {label}
    </button>
  );
};

export default Button;

// packages/dollhouse-designs/src/components/vue/Button.vue
<template>
  <button type="button" :class="classes" @click="onClick" :style="style">
    {{ label }}
  </button>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import '../styles/button.css';

interface Props {
  label: string;
  primary?: boolean;
  secondary?: boolean;
  danger?: boolean;
  size?: 'small' | 'medium' | 'large';
  backgroundColor?: string;
}

// Define the props for the component
const props = defineProps<Props>();

// Define emits for the component
const emit = defineEmits<{
  (e: 'click'): void;
}>();

// Compute the classes for the button based on props
const classes = computed(() => ({
  'button': true,
  'button-primary': props.primary && !props.danger && !props.secondary,
  'button-secondary': props.secondary && !props.primary && !props.danger,
  'button-danger': props.danger && !props.primary && !props.secondary,
  [`button-${props.size || 'medium'}`]: true,
}));

// Compute the style for the button based on the background color prop
const style = computed(() => ({
  backgroundColor: props.backgroundColor,
}));

// Handle button click and emit the click event
const onClick = () => {
  emit('click');
};
</script>
